"""Define enumeration constants for HTTP status Mozilla docs."""

from enum import StrEnum


class HTTPStatusDoc(StrEnum):
    """Enumeration of Mozilla documentation links for HTTP status codes."""

    STATUS_100 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/100"
    STATUS_101 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/101"
    STATUS_102 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/102"
    STATUS_200 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/200"
    STATUS_201 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201"
    STATUS_202 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/202"
    STATUS_203 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/203"
    STATUS_204 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204"
    STATUS_205 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/205"
    STATUS_206 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/206"
    STATUS_207 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/207"
    STATUS_208 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/208"
    STATUS_226 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/226"
    STATUS_300 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/300"
    STATUS_301 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301"
    STATUS_302 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302"
    STATUS_303 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/303"
    STATUS_304 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304"
    STATUS_305 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/305"
    STATUS_307 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307"
    STATUS_308 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308"
    STATUS_400 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400"
    STATUS_401 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401"
    STATUS_402 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/402"
    STATUS_403 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403"
    STATUS_404 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404"
    STATUS_405 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405"
    STATUS_406 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/406"
    STATUS_407 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/407"
    STATUS_408 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/408"
    STATUS_409 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409"
    STATUS_410 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/410"
    STATUS_411 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/411"
    STATUS_412 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/412"
    STATUS_413 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/413"
    STATUS_414 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/414"
    STATUS_415 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415"
    STATUS_416 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/416"
    STATUS_417 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/417"
    STATUS_418 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/418"
    STATUS_421 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/421"
    STATUS_422 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422"
    STATUS_423 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/423"
    STATUS_424 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/424"
    STATUS_425 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/425"
    STATUS_426 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/426"
    STATUS_428 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/428"
    STATUS_429 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429"
    STATUS_431 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/431"
    STATUS_451 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/451"
    STATUS_500 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500"
    STATUS_501 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/501"
    STATUS_502 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502"
    STATUS_503 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503"
    STATUS_504 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/504"
    STATUS_505 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/505"
    STATUS_506 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/506"
    STATUS_507 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/507"
    STATUS_508 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/508"
    STATUS_510 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/510"
    STATUS_511 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/511"
